config/routes.rb
Rails.application.routes.draw do
  root 'main#index'

  get "videos/:friendly_title/:id", to: 'videos#show', as: :friendly_video_title

  resources :videos, only: [:index]

  resources :playlists, only: [:show]

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :zype_cli
  before_filter :setup_presenters

  helper_method :group_by_category
  helper_method :filter_by_category
  helper_method :category_value

  private

  def zype_cli
    @zype ||= Zype::Client.new
  end

  def setup_presenters
    @layout = LayoutPresenter.new
  end

  def group_by_category(inputs,category)
    inputs.group_by{|v| category_value(v,category) }
  end

  def filter_by_category(inputs,category,value)
    inputs.select{|v| category_value(v,category).include?(value) }
  end

  def category_value(input,title)
    if input.categories && category = input.categories.detect{|c| c.title == title}
      category.value
    end
  end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
    @playlists = @zype.playlists(sort: 'priority', order: 'asc', per_page: 10)
  end

  private
  def setup_presenters
    @main = MainPresenter.new
    super
  end
end

app/controllers/playlists_controller.rb
class PlaylistsController < ApplicationController

  def show
    @playlist = @zype.playlists.find(params[:id])

    @count = 10
    @page = params[:page].present? ? params[:page] : 1
    @videos = @playlist.videos(page: @page, per_page: @count)
  end

end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  def index
    @count = 500
    @page = params[:page].present? ? params[:page] : 1

    @videos = @zype.videos.all(q: params[:q], page: @page, sort: 'title', per_page: @count)
  end

  def show
    @video = @zype.videos.find(params[:id])
  end

  private
  def setup_presenters
    @video_presenter = VideoPresenter.new
    super
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def time_to_midnight
    1.day.from_now.midnight.to_i - Time.now.to_i
  end

  def friendly_title(title)
    title.parameterize
  end

  def video_overlay(video)
    if video.thumbnails.blank?
      "white"
    elsif thumbnail = video_thumbnail_url(video, {width:426})
      "url('#{thumbnail}')"
    elsif thumbnail = video_thumbnail_url(video, {width:480})
      "url('#{thumbnail}')"
    end
  end

  def video_thumbnail_url(video, params={}, options={})
    return unless video.thumbnails

    image = if params[:width]
      video.thumbnails.detect{|t| t.width == params[:width]}
    elsif params[:height]
      video.thumbnails.detect{|t| t.height == params[:height]}
    else
      raise ArgumentError, "Height or width is required to detect thumbnail URL"
    end

    if image
      return image.url
    else
      return nil
    end
  end

  def video_image(video, title, options={})
    return nil if video.images.blank?

    if image = video.images.detect{|i| i.title == title}
      image_tag image.url, options
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Your Brand</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application'%>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render partial: 'shared/nav' %>
  <div class='container'>
    <%= yield %>
  </div>
  <%= render partial: 'shared/footer' %>
</body>
</html>

app/views/main/_main_playlists.html.erb
<% cache("layout/main/playlists", :expires_in => time_to_midnight) do %>
  <% @playlists.each do |playlist| %>
    <div class="slider-holder">
      <h2><%= link_to playlist.title, playlist_path(playlist._id) %></h2>
      <%= render partial: 'shared/playlist_slider', locals: {id:friendly_title(playlist.title), video_collection: playlist.videos} %>
    </div>
  <% end %>
<% end %>

app/views/main/index.html.erb
<%= render partial: 'main_playlists' %>

app/views/playlists/show.html.erb
<h1><%= @playlist.title.titleize %></h1>

<ul class='video-filters'>
  <div class="btn-group" role="group" aria-label="...">
    <button type="button" class="btn btn-default" data-filter='name'>Name</button>
    <button type="button" class="btn btn-default" data-filter='date'>Date</button>
    <button type="button" class="btn btn-default" data-filter='populatiry'>Popularity</button>
  </div>
</ul>

<div class="row" id='video-list'>
  <% @videos.each do |video| %>
  <div class='film-thumbnail-container col-md-3 col-sm-6' data-name='<%= video.title %>' data-date="<%= video.created_at %>" data-rating='<%= video.rating %>' data-popularity='<%= video.request_count %>'>
    <%= render partial: 'shared/video_thumbnail', locals: {video: video, truncate_length: 20} %>
  </div>
  <% end %>
</div>

<script>
$('ul.video-filters').on('click', '.btn', function(e){
  e.preventDefault();
  var filter = this.dataset.filter;
  var divList = $(".film-thumbnail-container");

  divList.sort(function(a, b){
    if(filter === 'name') {
      if($(b).data(filter) < $(a).data(filter)) return 1;
      if($(b).data(filter) > $(a).data(filter)) return -1;
      return 0;
    } else {
      if($(b).data(filter) < $(a).data(filter)) return -1;
      if($(b).data(filter) > $(a).data(filter)) return 1;
      return 0;
    }
  });
  $("#video-list").html(divList);
})
</script>

app/views/shared/_footer.html.erb
<footer class="footer">
  <div class="container">
    <p class="text-muted">&copy; 2014 Your Brand All Rights Reserved.</p>
  </div>
</footer>

app/views/shared/_nav.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">Your Brand</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to 'All Videos', videos_path %></li>
      </ul>
      <%= form_tag videos_path, method: 'get', class: 'navbar-form navbar-left' do %>
        <div class="form-group">
          <%= search_field_tag :q, params[:q], placeholder: 'Browse', class:'form-control' %>
        </div>
        <%= submit_tag 'Submit', class:'btn btn-default' %>
      <% end %>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/shared/_playlist_slider.html.erb
<div id='<%= id %>' class="owl-carousel playlist-container">
  <% video_collection.each do |video| %>
  <%= render partial: 'shared/video_thumbnail', locals: {video: video, truncate_length: 30} %>
  <% end %>
</div>
<script>
$('#'+'<%= id%>').owlCarousel({
  items : 3, //10 items above 1000px browser width
  itemsDesktop : [1000,3], //5 items between 1000px and 901px
  itemsDesktopSmall : [900,3], // betweem 900px and 601px
  itemsTablet: [600,2], //2 items between 600 and 0);
  navigation : true,
  navigationText: [
  '<span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>',
  '<span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>'
  ],
  scrollPerPage: true
});
</script>

app/views/shared/_video_thumbnail.html.erb
<div class= 'film-thumbnail'>
  <div class='film-thumbnail-title'>
    <h4><%= truncate(video.title, length: truncate_length) %></h4>
  </div>
  <%= link_to friendly_video_title_path(friendly_title: friendly_title(video.title), id: video._id) do %>
  <div class='overlayPic' style='background-image: <%= video_overlay(video) %>;'>
    <div class="film-description text-box">
      <p><%= truncate(video.description, length: 200) %></p>
    </div>
  </div>
  <% end %>
</div>

app/views/videos/index.html.erb
<h1>Browse Videos</h1>

<ul class='video-filters'>
  <div class="btn-group" role="group" aria-label="...">
    <button type="button" class="btn btn-default" data-filter='name'>Name</button>
    <button type="button" class="btn btn-default" data-filter='date'>Date</button>
    <button type="button" class="btn btn-default" data-filter='populatiry'>Popularity</button>
  </div>
</ul>

<div class="row" id='video-list'>
  <% @videos.each do |video| %>
    <div class='film-thumbnail-container col-md-3 col-sm-6' data-name='<%= video.title %>' data-date="<%= video.created_at %>" data-rating='<%= video.rating %>' data-popularity='<%= video.request_count %>'>
      <%= render partial: 'shared/video_thumbnail', locals: {video: video, truncate_length: 25} %>
    </div>
  <% end %>
</div>

<script>
$('ul.video-filters').on('click', '.btn', function(e){
  e.preventDefault();
  var filter = this.dataset.filter;
  var divList = $(".film-thumbnail-container");

  divList.sort(function(a, b){
    if(filter === 'name') {
      if($(b).data(filter) < $(a).data(filter)) return 1;
      if($(b).data(filter) > $(a).data(filter)) return -1;
      return 0;
    } else {
      if($(b).data(filter) < $(a).data(filter)) return -1;
      if($(b).data(filter) > $(a).data(filter)) return 1;
      return 0;
    }
  });
  $("#video-list").html(divList);
})
</script>

app/views/videos/show.html.erb
<h1><%= @video.title.titleize %></h1>

<div id='zype_player'></div>

<% if description = @video.description %>
<p class='video-description'>
  <%= truncate(description.html_safe, length: 400) %>
</p>
<% end %>
<script id='ZYPE_PLAYER_JS' src="https://player.zype.com/embed/<%= @video._id %>.js?player_key=<%= ENV['ZYPE_PLAYER_KEY'] %>&autoplay=true" type='text/javascript'></script>